"""Canonical cluster + profile templates. Single source of truth.

Used by `vctl init-config`; copied into `examples/` at release time.
"""

from __future__ import annotations

CLUSTER_TEMPLATE = """\
# vctl cluster.yaml — generated by `vctl init-config`.
# Schema version: vctl/v1
# Validate after editing: `vctl config validate cluster.yaml`
# Inspect resolved config (with env overrides): `vctl config show`
#
# Env overrides: VCTL_<SECTION>__<FIELD>=value (double-underscore = nested)
#   e.g. VCTL_LB__HOST=10.0.0.42
#        VCTL_LB__CLIENT__BIND_PORT=8000
#        VCTL_PROFILE=qwen3_5-9b  (or MODEL_PROFILE — alias)

apiVersion: vctl/v1
kind: Cluster

# Default profile loaded when --profile is not passed.
# Lookup order: --profile > VCTL_PROFILE > MODEL_PROFILE > this field.
profile: qwen3-vl-30b-a3b

cluster:
  # Path to the venv containing the vllm binary. `<venv>/bin` is prepended
  # to $PATH before the serve subprocess is spawned.
  venv: /mnt/umm/users/qianjianheng/workspace/vllm_test/.venv_0_19_2rc1

  # Shared FS directory for the atomic backend-state file
  # (`<lb.host>_backends.txt`). Must be writable by every pod that
  # calls `vctl lb add`, `attach`, etc. flock-based mutual exclusion.
  state_dir: /mnt/aigc/users/qianjianheng/.vllm-lb-state

  # Cluster-wide env vars merged into the vllm subprocess.
  # `profile.env` wins on conflicts.
  env: {}

lb:
  # LB implementation discriminator. v0.1.0 ships only `haproxy`.
  kind: haproxy

  # IP of the pod that runs haproxy. `vctl lb start` refuses unless
  # this pod's detected IP matches (override with --force).
  host: 10.119.30.181

  # Client-facing listener (what your app/curl hits).
  client:
    bind_port: 8080

  # Admin runtime API socket (TCP). Used by `vctl lb add/remove/drain` etc.
  # to talk to a remote haproxy without ssh.
  admin:
    bind_port: 9001

  # Web stats page. Open in browser: http://<lb.host>:<bind_port>/
  stats:
    bind_port: 9000

  # Load-balancing algorithm. Valid values:
  #   leastconn       pick backend with fewest active connections (default)
  #   roundrobin      strict round-robin
  #   random          power-of-2 random pick (rendered as `random(2)`)
  #   hdr:<header>    sticky by HTTP header value
  #                   e.g. `hdr:X-Session-Id` for session affinity
  algorithm: leastconn

  # Per-backend health check (HAProxy `httpchk`).
  health:
    # Path on each backend to probe.
    path: /health
    # Check interval.
    check_interval: 5s
    # Consecutive failures before marking the backend DOWN.
    fall: 3
    # Consecutive successes before marking the backend UP.
    rise: 2

  # Per-backend defaults applied to every `server` entry in haproxy.cfg.
  defaults:
    # Cap concurrent connections to a single backend (queues the rest).
    maxconn_per_backend: 256
    # Ramp traffic up over this period when a backend comes UP.
    slowstart: 30s
    # TCP connect timeout.
    timeout_connect: 5s
    # Idle client timeout — must be long enough for streaming.
    timeout_client: 1h
    # Server response timeout — same.
    timeout_server: 1h
"""

QWEN3_5_9B_PROFILE = """\
# vctl profile: Qwen3.5-9B (dense, text-only)
# Schema version: vctl/v1
# Apply: `vctl --profile qwen3_5-9b serve`  (or set as cluster.profile)

apiVersion: vctl/v1
kind: Profile

model:
  # HuggingFace repo or local path.
  name: Qwen/Qwen3.5-9B
  # OpenAI-compatible model_id exposed by `/v1/models`.
  # `_` instead of `.` for shell-friendly filename / cli arg.
  served_as: qwen3_5-9b

resources:
  # Total GPUs to claim on the host.
  num_gpus: 8
  # Subset of GPUs visible to vllm (matches num_gpus).
  cuda_visible_devices: "0,1,2,3,4,5,6,7"

parallelism:
  # Number of independent vllm engines (replicates model weights).
  data_parallel: 8
  # Tensor-parallel slices within each engine. data_parallel * tensor_parallel
  # must equal num_gpus.
  tensor_parallel: 1
  # Number of API-server workers. Default: data_parallel.
  api_server_count: 8

server:
  # Listening port for vllm OpenAI-compatible API.
  http_port: 8000

# Pass-through args appended to `vllm serve <model>`. Use kebab-case to
# match vllm CLI flag names. Booleans are rendered as `--flag=true|false`.
vllm_args:
  # Multimodal init flags. Even for text-leaning models, vllm registers
  # Qwen3.5-9B via the Qwen2VL family and runs multimodal init. These two
  # flags route the encoder + processor cache through shared memory so
  # multiple API server workers don't race on HF Hub downloads.
  mm-encoder-tp-mode: data
  mm-processor-cache-type: shm
  reasoning-parser: qwen3
  enable-prefix-caching: true
  async-scheduling: true

# Subprocess env vars. Merges over cluster.env (profile wins on conflicts).
env:
  VLLM_ENGINE_READY_TIMEOUT_S: 1800
"""

QWEN3_VL_30B_A3B_PROFILE = """\
# vctl profile: Qwen3-VL-30B-A3B-Thinking (MoE multimodal)
# Schema version: vctl/v1

apiVersion: vctl/v1
kind: Profile

model:
  name: Qwen/Qwen3-VL-30B-A3B-Thinking
  served_as: qwen3-vl-30b-a3b

resources:
  num_gpus: 8
  cuda_visible_devices: "0,1,2,3,4,5,6,7"

parallelism:
  # MoE 30B fits comfortably on 8x80GB with TP=2 inside each DP rank.
  data_parallel: 4
  tensor_parallel: 2
  api_server_count: 4

server:
  http_port: 8000

vllm_args:
  # Vision encoder follows the data-parallel axis (one encoder per DP rank).
  mm-encoder-tp-mode: data
  # Image preprocessor cache shared via /dev/shm (per pod).
  mm-processor-cache-type: shm
  reasoning-parser: qwen3
  enable-prefix-caching: true

env:
  # 30B model load takes longer; allow up to 50 minutes.
  VLLM_ENGINE_READY_TIMEOUT_S: 3000
"""

PROFILE_TEMPLATES: dict[str, str] = {
    "qwen3_5-9b": QWEN3_5_9B_PROFILE,
    "qwen3-vl-30b-a3b": QWEN3_VL_30B_A3B_PROFILE,
}
